export default {
  LOAD_COURSES_SUCCESS: 'LOAD_COURSES_SUCCESS',
  LOAD_AUTHORS_SUCCESS: 'LOAD_AUTHORS_SUCCESS',
  CREATE_COURSES_SUCCESS: 'CREATE_COURSES_SUCCESS',
  UPDATE_COURSES_SUCCESS: 'UPDATE_COURSES_SUCCESS',
  BEGIN_AJAX_CALL: 'BEGIN_AJAX_CALL',
  AJAX_CALL_ERROR: 'AJAX_CALL_ERROR'
};
